import { APP_NAME, URL_APP } from '@config'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a la <a href={URL_APP}>{APP_NAME}!</a>
        </h1>

        <p className={styles.description}>
          Comienza a registrar compras en {' '}
          <code className={styles.code}>compra-cliente-sitio</code>
        </p>

        <div className={styles.grid}>
          <Link href="/compra-cliente-sitio">
            <a className={styles.card}>
              <h2>Compra Cliente Sitio &rarr;</h2>
              <p>Registra la venta de tus productos en tu local físico.</p>
            </a>
          </Link>

          <Link href="/compras/resumen-compras">
            <a className={styles.card}>
              <h2>Resumen compras &rarr;</h2>
              <p>Encuentra aquí todas las compras realizadas por los clientes.</p>
            </a>
          </Link>


          {/* <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a> */}

          {/* <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a> */}

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.jhonsebastianas.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Creado con ❤ por {' '} @jhonsebastianas
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}
