import { APP_NAME, URL_APP } from '@config'
import Head from 'next/head'
import Link from 'next/link'
import MainLayout from 'src/layouts/main-layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <MainLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Bienvenido a la <Link href='/'><a>{APP_NAME}!</a></Link>
          </h1>

          <p className={styles.description}>
            Comienza a registrar compras en {' '}
            <code className={styles.code}>compra-cliente-sitio</code>
          </p>

          <div className={styles.grid}>
            <Link href="/compra-cliente-sitio">
              <a className={styles.card}>
                <h2>Compra Cliente Sitio &rarr;</h2>
                <p>Registra la venta de tus productos en tu local físico.</p>
              </a>
            </Link>

            <Link href="/compras/resumen-compras">
              <a className={styles.card}>
                <h2>Resumen compras &rarr;</h2>
                <p>Encuentra aquí todas las compras realizadas por los clientes.</p>
              </a>
            </Link>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://www.jhonsebastianas.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Creado con ❤ por {' '} @jhonsebastianas
            <span className={styles.logo}>
              {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
            </span>
          </a>
        </footer>
      </div>
    </MainLayout>
  )
}
